Parameters:
  BucketName: 
    Type: String
    Description:  Enter the name of bucket you want to create

Resources:
  MyProdS3bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName