Parameters:
    InstanceType:
        Type: String
        Description: Enter the ec2 instance type you want to launch
        Default: t3.micro
        AllowedValues:
            - t3.micro
            - c7i-flex.large
            - m7i-flex.large

    AvailabilityZone:
        Type: String
        Description: Enter the AZ for your instance
        Default: ap-south-1a
        AllowedValues:
            - ap-south-1a

    KeyPair:
        Type: String
        Description: Enter the AZ for your instance
        Default: awar08-kp

Resources: 
    MyProdEC2Instance:
        Type: AWS::EC2::Instance
        Properties:
            ImageId: ami-09ed39e30153c3bf9
            AvailabilityZone: !Ref AvailabilityZone
            InstanceType: !Ref InstanceType
            KeyName: !Ref KeyPair
Outputs:
    Ec2InstanceID:
        Description: The instance ID
        Value: !Ref MyProdEC2Instance