Parameters:

    VpcId:
        Type: AWS::EC2::VPC::Id

    InstanceType:
        Type: String
        Description: Enter the ec2 instance type you want to launch
        Default: t3.micro
        AllowedValues:
            - t3.micro
            - c7i-flex.large
            - m7i-flex.large

    AvailabilityZone:
        Type: String
        Description: Enter the AZ for your instance
        Default: ap-south-1a
        AllowedValues:
            - ap-south-1a

    KeyPair:
        Type: String
        Description: Enter the AZ for your instance
        Default: awar08-kp

Resources: 

    MyWaitHandle:
        Type: AWS::CloudFormation::WaitConditionHandle

    DemoSG:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Security group for demo
            VpcId: !Ref VpcId
            SecurityGroupIngress:
                - IpProtocol: tcp
                  FromPort: 22
                  ToPort: 22
                  CidrIp: 0.0.0.0/0

    MyWaitCondition:
        Type: AWS::CloudFormation::WaitCondition
        DependsOn: DemoSG
        Properties:
            Handle: !Ref MyWaitHandle
            Timeout: 60

    MyProdEC2Instance:
        Type: AWS::EC2::Instance
        Properties:
            ImageId: ami-09ed39e30153c3bf9
            AvailabilityZone: !Ref AvailabilityZone
            InstanceType: !Ref InstanceType
            KeyName: !Ref KeyPair
            SecurityGroupIds:
                - !Ref DemoSG
            Tags:
                - Key: Name
                  Value: !Sub "data-block-demo-${AvailabilityZone}"
Outputs:
    Ec2InstanceID:
        Description: The instance ID
        Value: !Ref MyProdEC2Instance