apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - name: nodeapp
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["node", "-e", "require('http').createServer((req, res) => res.end('Hello from K8s Class and we are delivering using custom helm chart!')).listen(3000)"]
          ports:
            - containerPort: 3000