apiVersion: v1
kind: Pod
metadata:
  name: success-test
  namespace: myapp
spec: 
  containers:
  - name: testconainer
    image: nginx
    ports:
    - containerPort: 80
    resources:
      limits:
        cpu: "500m"
        memory: "128Mi"
      requests:
        cpu: "250m"
        memory: "64Mi"