apiVersion: v1
kind: Pod
metadata:
  name: fail-test
  namespace: myapp
spec: 
  containers:
  - name: testconainer
    image: nginx
    ports:
    - containerPort: 80
    resources:
      limits:
        cpu: "2"
        memory: "2Gi"
      requests:
        cpu: "2"
        memory: "2Gi"