apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  DB_USERNAME: "dbadmin"
  DB_PORT: "3306"
  DB_ENV: "production"

#kubectl create configmap app-config --from-literal=DB_ENV=production --from-literal=DB_PORT=3306

---
#Method 1 : We can add config map as env variable to the pod.

apiVersion: v1
kind: Pod
metadata:
  name: app-pod
spec:
  containers:
  - name: busybox
    image: busybox:latest
    command: ["sh", "-c", "echo Hello from $DB_ENV && sleep 120"]
    envFrom:
      - configMapRef:
          name: app-config

---
#method-2: We can mount entire config map as a file

apiVersion: v1
kind: Pod
metadata:
  name: app-pod2
spec:
  containers:
  - name: busybox
    image: busybox:latest
    command: ["sh", "-c", "echo Hello from $DB_ENV && sleep 120"]
    volumeMounts:
      - name: configmap-volume
        mountPath: /etc/config
  volumes:
    - name: configmap-volume
      configMap:
        name: app-config

---
#method-3: We can pick specific key from config map and use as env var

apiVersion: v1
kind: Pod
metadata:
  name: app-pod3
spec:
  containers:
  - name: busybox
    image: busybox:latest
    command: ["sh", "-c", "echo Hello from $ENVIRONEMNT && sleep 120"]
    env:
      - name: ENVIRONEMNT
        valueFrom:
          configMapKeyRef:
            name: app-config
            key: DB_ENV