AWSTemplateFormatVersion: '2010-09-09'
Description: Aviz Academy - Child Stack 1 - IAM Role

Resources:

  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2Role

Outputs:

  InstanceProfileName:
    Description: Pass this to EC2 child stack
    Value: !Ref EC2InstanceProfile
